package com.aau.moodle20.constants;

public interface ApiErrorResponseCodes {

    Integer INVALID_METHOD_PARAMETER = 460;
    Integer API_NOT_FOUND = 461;
    Integer USER_ALREADY_EXISTS = 462;


    Integer USERNAME_ALREADY_EXISTS = 470;
    Integer MATRICULATION_NUMBER_ALREADY_EXISTS = 471;
    Integer SEMESTER_ALREADY_EXISTS = 472;
    Integer COURSE_IN_SEMESTER_ALREADY_EXISTS = 473;
    Integer CHANGED_COURSE_NUMBER_ALREADY_EXISTS = 474;
    Integer COPIED_COURSE_NUMBER_ALREADY_EXISTS = 475;
    Integer TEMPORARY_PASSWORD_EXPIRED = 480;

    Integer REGISTER_USERS_WRONG_MATRICULATION_NUMBER_FORMAT = 481;
    Integer REGISTER_USERS_MATRICULATION_ALREADY_EXISTS = 482;
    Integer REGISTER_USERS_USERNAME_ALREADY_EXISTS = 483;
    Integer EXERCISE_SHEET_WITH_THIS_NAME_ALREADY_EXISTS = 484;

    Integer EXAMPLE_WITH_THIS_NAME_ALREADY_EXISTS = 485;
    Integer SUB_EXAMPLE_WITH_THIS_NAME_ALREADY_EXISTS = 486;
    Integer NO_VALID_VALIDATOR_FOUND_IN_JAR = 487;
}
