sudo: required
language: java
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
jdk:
  - openjdk8
before_install: npm i -g npm@^3
install:
  - cd ./frontend
  - npm install
  - npm run build
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script: mvn clean install