sudo: required
language: java
addons:
  chrome: stable
  sonarcloud:
    organization: "kirdock"
    token:
      secure: "C2RAUdJQHCP1dwI8jUquNsaKnQJUwZlwRkNBvYQsa3esEKwy70EYm45EhkCT3o8zZzCgPGikeEwBM1NyNFOdYUvo84fL8tqKg+Dj6TS2Z2PgNSdbzAsKOEGC3HRuvvJw5tV3T385OHnd00jxk6bkvVjolG9IaVGprjPgvaqXr+PP8orQPkx6NWsb0QhvAOtWlGeT0sYL0XzOfhwgs/JOzSELPagzSBwKu4I2wyL0+8g+ZwBBoOr2GncDULhT6QS6mddeQH/OQPFlYkQXXbk8miIddjk0oIvRk+F+xpSt0lauwXLMXOYHDEgA44boTknWC6BmHxI/myfNN2PyOKS3xoem7hjnVTCiRoSsM5O/HVGRES8uWF03J7WkfQlfDiO8uEJFMCclsa1935B0Mr71ArWoMq6aWJa7By910t/Svyp7pMKqWFOL53P8gZWJGkLVLItlqhRs5KZJMS4YSBMSqga8BtJB5CSJSb8GBr92JZu1FFb+ZK9FZ2kjIyTNJ+eed0mkPAQ6ZJ7/fbiFgIllCSqRhhZFqZVPNJJpg+M6lon01/cEVdyGoAkMdqrHFsm3x9QtFWCqktPzhoF5uJGuU/qFFnWYbxYWlPrlkKd3NyCs9gajJbCN1NK3DaoWaTdhzX2U77ZYvpTiEVgxjW+F6dtNHw905pzvEdiLlrdJDXk="
jdk:
  - oraclejdk11

services:
  - xvfb

before_script:
  - export DISPLAY=:99.0
  - npm i -g npm@^6
  - sleep 3

script:
  - mvn clean install
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Kirdock_Moodle2.0