language: java
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
jdk:
  - openjdk8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^3
  - sleep 3

script: mvn clean install