DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(120) NOT NULL,
  username VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS ROLE;

CREATE TABLE ROLE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(50)
);


DROP TABLE IF EXISTS USER_ROLE;

CREATE TABLE USER_ROLE (
  user_id INT NOT NULL,
  role_id INT NOT NULL
);


